#!/usr/bin/env bash
set -e
set -u
set -o pipefail

rg --color=always --line-number --no-heading --smart-case "$1" ~/Documents/Notes | fzf -d':' --ansi --preview "command bat -p --color=always {1} --highlight-line {2}" --preview-window ~8,+{2}-5 | awk -F':' '{print $1}'
