#!/usr/bin/env bash
set -o pipefail

# Parse command line arguments
USE_CHOOSE=false
if [ "$1" = "-ui" ]; then
    USE_CHOOSE=true
fi

# Get the query from all arguments
query="$*"

# Get search query
if [ -z "$query" ]; then
    if [ "$USE_CHOOSE" = true ]; then
        query=$(osascript -e 'text returned of (display dialog "Enter search query:" default answer "")')
    else
        query=$(echo "" | fzf --prompt="Enter search query: " --print-query | tail -n1)
    fi
fi

declare -a SEARCH_ENGINES=(
    "amazon https://www.amazon.com/s?k="
    "bbc https://www.bbc.co.uk/search?q="
    "brave https://search.brave.com/search?q="
    "coinmarketcap https://coinmarketcap.com/currencies/"
    "duckduckgo https://duckduckgo.com/?q="
    "ebay https://www.ebay.com/sch/i.html?_nkw="
    "ecosia https://www.ecosia.org/search?q="
    "github https://github.com/search?q="
    "goodreads https://www.goodreads.com/search?q="
    "google https://www.google.com/search?q="
    "googlefinance https://www.google.com/finance/quote/"
    "googleimages https://www.google.com/images?q="
    "googlemaps https://www.google.com/maps/search/"
    "googlenews https://news.google.com/search?q="
    "googletranslate https://translate.google.com/?sl=auto&tl=en&text="
    "grok https://grok.com/search?q="
    "imdb https://www.imdb.com/find?q="
    "linkedin https://www.linkedin.com/search/results/all/?keywords="
    "pinterest https://www.pinterest.com/search/pins/?q="
    "reddit https://www.reddit.com/search/?q="
    "startpage https://www.startpage.com/do/search?q="
    "stackoverflow https://stackoverflow.com/search?q="
    "twitter https://twitter.com/search?q="
    "wikipedia https://en.wikipedia.org/w/index.php?search="
    "yahoo https://search.yahoo.com/search?p="
    "youtube https://www.youtube.com/results?search_query="
)

# Select search engine
if [ -z "$engine" ]; then
    if [ "$USE_CHOOSE" = true ]; then
        engine=$(printf "%s\n" "${SEARCH_ENGINES[@]}" | cut -d' ' -f1 | choose)
    else
        engine=$(printf "%s\n" "${SEARCH_ENGINES[@]}" | cut -d' ' -f1 | fzf --prompt="Select search engine: ")
    fi
fi

engine_url=$(printf "%s\n" "${SEARCH_ENGINES[@]}" | grep "^${engine} " | cut -d' ' -f2-)

search_url="${engine_url}$(echo "$query" | sed 's/ /%20/g')"
echo "Opening: $search_url"
open -a "Brave Browser" "$search_url"
